name: laavi_window
description: A new Flutter FFI plugin project.
version: 0.0.1

environment:
  sdk: '>=2.18.0-109.0.dev <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  win32: ^2.7.0
  ffi: ^2.0.0

dev_dependencies:
  ffigen: ^4.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: LaaviWindowPlugin
